apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopus-app
  namespace: argocd # Ensure the Argo CD namespace is correct
  annotations: 
    octopus.com/project: "jt-s-argo-stuff"
    octopus.com/environment: "development"
spec:
  project: default # Or the name of your Argo CD project
  source:
    repoURL: 'https://github.com/Jtango18/jt-argo-test.git' # Replace with your Git repository URL
    targetRevision: main
    path: octopus-app # The path to the manifests within the repository
  destination:
    server: 'https://kubernetes.default.svc' # Or the address of your Kubernetes API server
    namespace: octopus-managed-app # The namespace where you want to deploy the app
  syncPolicy:
    automated:
      prune: true    # Delete resources no longer present in Git
      selfHeal: true # Reconcile resources back to the desired state
    syncOptions:
    - CreateNamespace=true # Automatically create the destination namespace if it doesn't exist
